name: Pull Request

on: [pull_request]

jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Build
        run: go build -o gocrane .

      - name: Get Ginkgo
        run: go install github.com/onsi/ginkgo/ginkgo@latest

      - name: Run Tests
        run: ginkgo -r --race --randomizeAllSpecs --randomizeSuites
