name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Build
        env:
          GO111MODULE: on
        run: go build -o gocrane .
