name: Pull Request

on: [pull_request]

jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Download Dependencies
        run: go mod download

      - name: Run Tests
        run: go run github.com/onsi/ginkgo/v2/ginkgo -r --race --randomize-all --randomize-suites

      - name: Build
        run: go build -o gocrane .
